name: medicine_warehouse
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  easy_localization: ^3.0.0


  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  provider: ^6.1.1
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  shared_preferences:
  flutter_secure_storage:

  flutter_barcode_scanner: ^2.0.0
  dio: ^5.3.3
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  flutter_lints: ^2.0.0

  flutter_localizations:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:

    - assets/l10n/
    - assets/images/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Book.otf
    - family: Messiri
      fonts:
        - asset: assets/fonts/Messiri/ElMessiri-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
